### PR TITLE
[OPS-8583] Drupal 10 update

### PR DESCRIPTION
**Pull request by orakili**
Refs: OPS-8583

Same thing as https://github.com/UN-OCHA/drupal-starterkit/pull/4 but for Drupal 10 and using the PHP 8.1 image.

The composer.json uses a custom script that is equivalent to https://github.com/mglaman/composer-drupal-lenient in order to allow installing modules that are not yet compatible with Drupal 10 and the https://github.com/orakili/composer-drupal-info-file-patch-helper plugin to fix an issue that prevents applying the Drupal 10 compatibility patches (ex: those generated automatically by Drupal rector).

### CODE REVIEW

**Review by left23 — APPROVED** [review]
Worked for me. I have a local site running.

I'm wondering is the pattern [site-name]-local.test for the URL necessary? I think for the stacks it's usually without the "local" so just `site-name.test`
Keeping this as close to the stack set up as possible IMO prevents extra cognitive load caused by differences that don't necessarily need to be different... Unless I am missing the reasoning behind this.

**Comment by lazysoundsystem** [comment]
@orakili - sounds like a good idea if we can just have the site repo and not maintain a separate stack repo for local development. I'll have another look at this and we can discuss further.

**Comment by left23** [comment]
@orakili No preference from me, the question was mostly a curiosity so thanks for explaining your reasoning.

BTW a few weeks ago when I wanted to set up a D9 site for testing stuff, I used this repo (pre-D10) and https://github.com/UN-OCHA/local-reverse-proxy/tree/main/new-site-template and it worked well, because I was familiar with the stack set up having gone through it many times now. Any further moves to consolidate and/or simplify is always welcome IMO.
I also noticed that Cafuego mentioned he copied the stack from RWR for the new UNOCHA. RWR is a copy of the `local-reverse-proxy` template (at least it was initially) but this indicated that perhaps the `local-reverse-proxy` template isn't being used as a starting point as often as intended.

**Comment by orakili** [comment]
@lazysoundsystem I'm merging this PR. `main` is now for Drupal 10 and the [D9](https://github.com/UN-OCHA/drupal-starterkit/tree/D9) branch is for Drupal 9.

**Pull request merged**
