### PR TITLE
chore: change capitalization of patches dir for consistency

### PR DESCRIPTION
**Pull request by lazysoundsystem**
Refs: OPS-9075

We currently have two parallel conventions for naming the `patches` directory - capitalized or not. Happy to go through the make the others lowercase, or can uppercase the ones for unocha-site and rwint9-site. What do you think @orakili ?

### CODE REVIEW

**Comment by orakili** [comment]
@lazysoundsystem I have a preference for lowercase because it's less in the face and feels more consistent with the other folders but if it's easier to change UNO and RW then go for it.

**Comment by lazysoundsystem** [comment]
I'm happy to change the larger number of repos - @cafuego do you have an opinion on this not very important question?

**Comment by cafuego** [comment]
Non.

**Comment by lazysoundsystem** [comment]
This got committed as part of https://github.com/UN-OCHA/drupal-starterkit/pull/34. (We went with capital letters because most of the others were already using that, but I can change all back to lowercase if we want.) 

Closing.

**Pull request closed without merging**
